export const ACTORS = [
    {
        id: '1',
        name: 'Leonardo DiCaprio',
        gender: 'Male',
        birthday: '11-11-1974',
        birthplace: 'Los Angeles, California, USA',
        popularity: 9.8,
        biography: 'Leonardo DiCaprio is one of the most acclaimed actors of his generation. He began his career with small television roles before landing his breakthrough role in "What\'s Eating Gilbert Grape" (1993), earning his first Academy Award nomination at just 19. His collaboration with director James Cameron in "Titanic" (1997) made him a global superstar. Known for his intense preparation and method acting approach, DiCaprio has delivered unforgettable performances in films such as "The Aviator", "The Departed", "Inception", "The Wolf of Wall Street", and "The Revenant", for which he finally won the Academy Award for Best Actor in 2016. Off-screen, he is a passionate environmental activist and founder of the Leonardo DiCaprio Foundation, dedicated to protecting the world\'s last wild places.',
        picture: 'https://image.tmdb.org/t/p/w500/wo2hJpn04vbtmh0B9utCFdsQhxM.jpg',
    },
    {
        id: '3',
        name: 'Tom Hanks',
        gender: 'Male',
        birthday: '09-07-1956',
        birthplace: 'Concord, California, USA',
        popularity: 9.6,
        biography: 'Tom Hanks is one of the most beloved and recognizable actors in Hollywood history. He became the first actor since Spencer Tracy to win back-to-back Academy Awards for Best Actor, taking home the award for "Philadelphia" (1993) and "Forrest Gump" (1994). Known for his extraordinary range and genuine warmth on screen, Hanks has starred in some of the most commercially successful and critically acclaimed films of all time, including "Cast Away", "Saving Private Ryan", "The Green Mile", "Captain Phillips", and the "Toy Story" franchise as the voice of Woody. Off-screen, he is equally admired for his humility, kindness, and dedication to his craft, widely considered one of the nicest people in show business.',
        picture: 'https://image.tmdb.org/t/p/w500/xndWFsBlClOJFRdhSt4NBwiPq2o.jpg',
    },
    {
        id: '7',
        name: 'Brad Pitt',
        gender: 'Male',
        birthday: '18-12-1963',
        birthplace: 'Shawnee, Oklahoma, USA',
        popularity: 9.3,
        biography: 'Brad Pitt is one of Hollywood\'s most enduring and versatile stars, equally admired for his leading man charisma and his willingness to take on challenging, unconventional roles. He first gained widespread attention with "Thelma & Louise" (1991) and became a global superstar with films like "Se7en", "Fight Club", and "Troy". He won the Academy Award for Best Supporting Actor for "Once Upon a Time in Hollywood" (2019) and produced "12 Years a Slave", which won Best Picture. Known for his ability to seamlessly blend commercial appeal with artistic integrity, Pitt has delivered standout performances across multiple genres. He is also a passionate architecture enthusiast and the founder of Plan B Entertainment.',
        picture: 'https://image.tmdb.org/t/p/w500/cckcYc2v0yh1tc9QjRelptcOBko.jpg',
    },
    {
        id: '10',
        name: 'Scarlett Johansson',
        gender: 'Female',
        birthday: '22-11-1984',
        birthplace: 'New York City, New York, USA',
        popularity: 9.2,
        biography: 'Scarlett Johansson is one of the highest-grossing actresses in Hollywood history and a defining presence in modern cinema. She began acting as a child and quickly established herself as a serious dramatic actress with acclaimed performances in "Lost in Translation" (2003) and "Girl with a Pearl Earring" (2003). She became a global phenomenon through her role as Natasha Romanoff / Black Widow in the Marvel Cinematic Universe, a role she has reprised across over ten films. She received Academy Award nominations for both "Marriage Story" and "Jojo Rabbit" in the same year (2019), demonstrating her remarkable dramatic range. She is also a passionate advocate for gender pay equality in Hollywood.',
        picture: 'https://image.tmdb.org/t/p/w500/6NsMbJXRlDZuDzatN2akFdGuTvx.jpg',
    },
    {
        id: '18',
        name: 'Margot Robbie',
        gender: 'Female',
        birthday: '02-07-1990',
        birthplace: 'Dalby, Queensland, Australia',
        popularity: 9.0,
        biography: 'Margot Robbie is one of the most exciting and versatile actresses to emerge in Hollywood in recent years. Born in regional Queensland, Australia, she began acting in Australian television before relocating to the United States. She burst onto the global stage opposite Leonardo DiCaprio in "The Wolf of Wall Street" (2013) and has not slowed down since. She received Academy Award nominations for "I, Tonya" (2017), in which she played figure skater Tonya Harding, and "Bombshell" (2019). Her portrayal of Harley Quinn in the DC Extended Universe became iconic, and her starring role in "Barbie" (2023) broke box office records worldwide. She is also an accomplished producer through her company LuckyChap Entertainment.',
        picture: 'https://image.tmdb.org/t/p/w500/euDPyqLnuwaWMHajcU3oZ9uZezR.jpg',
    },
    {
        id: '20',
        name: 'Timothée Chalamet',
        gender: 'Male',
        birthday: '27-12-1995',
        birthplace: 'New York City, New York, USA',
        popularity: 9.2,
        biography: 'Timothée Chalamet is the most exciting young talent in Hollywood and widely regarded as the defining actor of his generation. Born in New York City to a French father and American mother, he grew up between the two countries and developed a deep passion for the arts from an early age. He became the youngest actor ever nominated for the Academy Award for Best Actor for his devastating performance in "Call Me by Your Name" (2017) at just 22 years old. He followed this with acclaimed roles in "Little Women", "Beautiful Boy", and "The King". His casting as the young Paul Atreides in Denis Villeneuve\'s "Dune" (2021) and its sequel established him as a major blockbuster star, while his performance as a young Willy Wonka demonstrated his remarkable charm and versatility.',
        picture: 'https://image.tmdb.org/t/p/w500/BE2sdjpgsa2rNTFa66f7upkaOP.jpg',
    },
];