export const MOVIES = [
    {
        id: '1',
        title: 'Interstellar',
        year: '2014',
        rating: '8.6',
        genre: 'Sci-Fi / Drama',
        poster: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
        description: 'In the near future, Earth is dying. Crops are failing, dust storms are consuming cities, and humanity faces extinction. Cooper, a former NASA pilot turned farmer, stumbles upon a secret NASA facility and is recruited for a desperate mission: travel through a wormhole near Saturn to find a new home for mankind. As Cooper and his crew venture into unknown galaxies, time itself becomes their greatest enemy. Back on Earth, his daughter Murph races to solve a gravity equation that could save humanity. A breathtaking exploration of love, sacrifice, and the resilience of the human spirit across the boundaries of space and time.',
    },
    {
        id: '2',
        title: 'The Dark Knight',
        year: '2008',
        rating: '9.0',
        genre: 'Action / Crime',
        poster: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
        description: 'Batman has established himself as Gotham\'s protector, working alongside District Attorney Harvey Dent and Lieutenant Gordon to dismantle organized crime. But a new threat emerges in the form of the Joker, a mysterious and anarchic criminal mastermind who thrives on chaos and has no motive beyond watching the world burn. As the Joker systematically tears apart everything Batman holds dear, Bruce Wayne must confront a profound moral dilemma: how far is he willing to go to protect the city he loves? A gripping crime epic that redefines what a superhero film can be.',
    },
    {
        id: '3',
        title: 'Inception',
        year: '2010',
        rating: '8.8',
        genre: 'Sci-Fi / Thriller',
        poster: 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
        description: 'Dom Cobb is a skilled thief who specializes in the art of extraction — stealing valuable secrets from deep within the subconscious mind during the dream state. His rare ability has made him a coveted player in the dangerous world of corporate espionage, but it has also cost him everything he loves. Now Cobb is offered a chance at redemption: instead of stealing an idea, he must plant one. If he succeeds, it will be the perfect crime. But no amount of preparation can ready his team for the dangerous enemy that seems to predict their every move — an enemy that only Cobb could have seen coming.',
    },
    {
        id: '4',
        title: 'Oppenheimer',
        year: '2023',
        rating: '8.3',
        genre: 'Biography / Drama',
        poster: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
        description: 'J. Robert Oppenheimer was a theoretical physicist who led the Manhattan Project, the top-secret World War II program that developed the first nuclear weapons. Driven by the fear that Nazi Germany was building its own atomic bomb, Oppenheimer assembled the greatest scientific minds of the era in the remote desert of Los Alamos, New Mexico. The Trinity test in July 1945 proved devastatingly successful. But as the bombs fell on Hiroshima and Nagasaki, Oppenheimer was haunted by the destruction he had unleashed. A profound meditation on genius, guilt, and the irreversible consequences of scientific ambition.',
    },
    {
        id: '5',
        title: 'The Shawshank Redemption',
        year: '1994',
        rating: '9.3',
        genre: 'Drama',
        poster: 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
        description: 'Andy Dufresne, a successful banker, is sentenced to two consecutive life terms in Shawshank State Penitentiary for the murders of his wife and her lover, despite his claims of innocence. Inside the brutal prison walls, Andy slowly gains the respect of his fellow inmates, including the wise and resourceful Ellis "Red" Redding. Over the years, Andy\'s quiet intelligence and unbreakable spirit reshape the lives of those around him. A timeless story about the enduring power of hope, friendship, and the indomitable human will to survive even in the darkest of circumstances.',
    },
    {
        id: '7',
        title: 'Pulp Fiction',
        year: '1994',
        rating: '8.9',
        genre: 'Crime / Drama',
        poster: 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
        description: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption in Los Angeles. Vincent Vega and Jules Winnfield are philosophical hitmen who quote scripture before carrying out their work. Butch Coolidge is a boxer who double-crosses his boss. Mia Wallace is the dangerous wife of a crime lord who gets too close to Vincent. Told in non-linear fashion with razor-sharp dialogue and shocking twists, Pulp Fiction revolutionized independent cinema and remains one of the most influential films ever made.',
    },
    {
        id: '8',
        title: 'Fight Club',
        year: '1999',
        rating: '8.8',
        genre: 'Drama / Thriller',
        poster: 'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
        description: 'An insomniac office worker, suffocating under the weight of consumerism and a meaningless existence, forms an underground fight club with a charismatic soap salesman named Tyler Durden. What begins as a raw, therapeutic outlet for disillusioned men quickly spirals into something far more dangerous and anarchic. As the club grows into a nationwide movement, the narrator begins to question everything he thought he knew about Tyler, himself, and reality. A visceral, provocative exploration of masculinity, identity, and the emptiness lurking beneath modern society\'s polished surface.',
    },
    {
        id: '9',
        title: 'The Matrix',
        year: '1999',
        rating: '8.7',
        genre: 'Sci-Fi / Action',
        poster: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
        description: 'Thomas Anderson is a mild-mannered software engineer by day and a hacker named Neo by night. His world is shattered when the enigmatic Morpheus offers him a choice between two pills: the blue pill to forget everything, or the red pill to discover the terrifying truth. Neo learns that the world he knows is an elaborate simulation called the Matrix, designed to keep humans enslaved while machines harvest their energy. Guided by Morpheus and the fierce Trinity, Neo must embrace his destiny as "The One" and wage war against the machines in a mind-bending battle for human freedom.',
    },
    {
        id: '10',
        title: 'Forrest Gump',
        year: '1994',
        rating: '8.8',
        genre: 'Drama / Romance',
        poster: 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
        description: 'Forrest Gump is a simple man from Alabama with a low IQ but an enormous heart, who witnesses and influences some of the most defining events of the 20th century without ever fully understanding their significance. From meeting Elvis Presley to serving in Vietnam, from running across America to becoming a ping-pong champion, Forrest stumbles through history with unshakeable optimism. Throughout it all, his one constant is his deep, unconditional love for his childhood friend Jenny. A magical and deeply moving film about the randomness of life, the power of kindness, and the extraordinary things ordinary people can achieve.',
    },
    {
        id: '11',
        title: 'Goodfellas',
        year: '1990',
        rating: '8.7',
        genre: 'Crime / Biography',
        poster: 'https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
        description: 'Henry Hill always wanted to be a gangster. Growing up in Brooklyn, he is seduced by the glamour and power of the local mob and begins working for them as a teenager. Over the decades, Henry rises through the ranks alongside his volatile best friend Jimmy Conway and the psychopathic Tommy DeVito. The money flows freely, the lifestyle is intoxicating, and violence is always just beneath the surface. But as drug addiction and paranoia set in, Henry\'s world begins to collapse from the inside. Based on a true story, Goodfellas is an electrifying portrait of the American mob at its most seductive and most brutal.',
    },
    {
        id: '12',
        title: 'Schindler\'s List',
        year: '1993',
        rating: '9.0',
        genre: 'Biography / Drama',
        poster: 'https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
        description: 'Oskar Schindler is a greedy German businessman who arrives in Krakow during World War II intent on making his fortune by exploiting cheap Jewish labor. He opens a factory and employs hundreds of Jewish workers from the local ghetto. But as the Nazi genocide accelerates and the horrors of the Holocaust become impossible to ignore, Schindler undergoes a profound moral transformation. He begins bribing SS officers and spending his entire fortune to protect his workers from the death camps. By the war\'s end, he has saved over a thousand lives. A devastating and deeply human testament to one man\'s capacity for redemption.',
    },
    {
        id: '13',
        title: 'The Silence of the Lambs',
        year: '1991',
        rating: '8.6',
        genre: 'Thriller / Crime',
        poster: 'https://image.tmdb.org/t/p/w500/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg',
        description: 'Clarice Starling is a young FBI trainee assigned to help catch a serial killer known as Buffalo Bill, who skins his female victims. To gain insight into the killer\'s psychology, she is sent to interview the brilliant but terrifying Dr. Hannibal Lecter, a former psychiatrist who is himself a cannibalistic serial killer now imprisoned in a high-security asylum. As Clarice peels back the layers of both cases, a deeply unsettling cat-and-mouse game develops between her and Lecter. A masterclass in psychological horror that is as much a study of character as it is a thriller.',
    },
    {
        id: '14',
        title: 'Se7en',
        year: '1995',
        rating: '8.6',
        genre: 'Crime / Thriller',
        poster: 'https://image.tmdb.org/t/p/w500/6yoghtyTpznpBik8EngEmJskVUO.jpg',
        description: 'Two detectives — the world-weary veteran Somerset and the idealistic newcomer Mills — are assigned to investigate a series of gruesome murders in a rain-soaked, unnamed city. Each killing is staged to represent one of the seven deadly sins: gluttony, greed, sloth, pride, lust, envy, and wrath. The killer is methodical, highly intelligent, and seems always one step ahead. As the detectives close in, the investigation takes a deeply personal and horrifying turn. A relentlessly dark and oppressive thriller that builds to one of the most shocking and memorable endings in cinema history.',
    },
    {
        id: '15',
        title: 'Gladiator',
        year: '2000',
        rating: '8.5',
        genre: 'Action / Drama',
        poster: 'https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg',
        description: 'Maximus is one of Rome\'s most capable and beloved generals, commanding the armies of Emperor Marcus Aurelius. But when the Emperor\'s corrupt son Commodus murders his father, seizes power, and orders the execution of Maximus and his family, the general is captured and sold into slavery. Stripped of everything, Maximus rises through the brutal ranks of the gladiatorial arena, forging a new identity as a warrior of the Colosseum. Driven by grief and an unquenchable thirst for justice, he fights his way back toward the man who destroyed his life. A thunderous epic of honor, vengeance, and sacrifice.',
    },
    {
        id: '17',
        title: 'Parasite',
        year: '2019',
        rating: '8.5',
        genre: 'Thriller / Drama',
        poster: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
        description: 'The Kim family lives in a cramped semi-basement apartment, scraping together a living by folding pizza boxes. When the son Ki-woo is recommended for a tutoring job at the wealthy Park family\'s mansion, he sees an opportunity too good to pass up. One by one, the Kims scheme their way into the Parks\' household, posing as unrelated skilled professionals. What begins as a darkly comic tale of class aspiration slowly transforms into something far more sinister when a shocking secret hidden beneath the mansion changes everything. A genre-defying masterpiece that cuts to the heart of global inequality.',
    },
    {
        id: '18',
        title: 'Whiplash',
        year: '2014',
        rating: '8.5',
        genre: 'Drama / Music',
        poster: 'https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg',
        description: 'Andrew Neiman is a driven first-year student at a prestigious New York music conservatory who dreams of becoming one of the great jazz drummers. His world is upended when he is selected to join the studio band of Terence Fletcher, the school\'s most feared and respected instructor. Fletcher\'s teaching methods are savagely abusive — he hurls chairs, screams insults, and pushes his students to the point of psychological and physical breakdown. As Andrew becomes consumed by his ambition and the need to earn Fletcher\'s approval, the line between dedication and self-destruction blurs completely. A visceral, pulse-pounding film about the cost of greatness.',
    },
    {
        id: '19',
        title: 'Memento',
        year: '2000',
        rating: '8.4',
        genre: 'Mystery / Thriller',
        poster: 'https://image.tmdb.org/t/p/w500/yuNs09hvpHVU1cBTCAk9zxsL2oW.jpg',
        description: 'Leonard Shelby suffers from a rare condition that prevents him from forming new memories. Since the night his wife was murdered, he has been unable to remember anything that happened more than a few minutes ago. To cope, he relies on an elaborate system of Polaroid photographs, notes, and tattoos covering his body to track clues about his wife\'s killer. As Leonard pieces together the mystery of what happened that night, the audience is taken on the same disorienting journey — told in reverse chronological order, the film brilliantly implicates the viewer in Leonard\'s fragile and unreliable perception of reality.',
    },
   
];