export const MOVIES = [
        {
            id: '1',
            title: 'Interstellar',
            year: '2014',
            rating: '8.6',
            genre: 'Sci-Fi / Drama',
            poster: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
        },
        {
            id: '2',
            title: 'The Dark Knight',
            year: '2008',
            rating: '9.0',
            genre: 'Action / Crime',
            poster: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
        },
        {
            id: '3',
            title: 'Inception',
            year: '2010',
            rating: '8.8',
            genre: 'Sci-Fi / Thriller',
            poster: 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
        },
        {
            id: '5',
            title: 'Oppenheimer',
            year: '2023',
            rating: '8.3',
            genre: 'Biography / Drama',
            poster: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
        },
        {
            id: '6',
            title: 'Interstellar',
            year: '2014',
            rating: '8.6',
            genre: 'Sci-Fi / Drama',
            poster: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
        },
        {
            id: '7',
            title: 'The Dark Knight',
            year: '2008',
            rating: '9.0',
            genre: 'Action / Crime',
            poster: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
        },
        {
            id: '8',
            title: 'Inception',
            year: '2010',
            rating: '8.8',
            genre: 'Sci-Fi / Thriller',
            poster: 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
        },
        {
            id: '9',
            title: 'Oppenheimer',
            year: '2023',
            rating: '8.3',
            genre: 'Biography / Drama',
            poster: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
        },
        
    ];